spring:
  application:
    name: email-dispatcher-api
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

crm:
  provider: ${CRM_PROVIDER:PLOOMES}
  ploomes:
    name: ${CRM_PLOOMES_NAME:ploomes}
    url: ${CRM_PLOOMES_URL:https://public-api2.ploomes.com}
    token: ${CRM_PLOOMES_TOKEN}

logging:
  level:
    com.infnet.emaildispatcher.adapter.out.http.crm.ploomes: DEBUG
rabbitmq:
  exchange: email-exchange
  queue:
    email-generation: email-generation-queue
  routing-key:
    email-generation: email.generation